name: renovate
on:
  schedule:
    - cron: '0 12,14 * * 1'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: renovate
        uses: renovatebot/github-action@v43.0.7
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
