name: shellcheck
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
